# Generated by Django 3.2.20 on 2023-09-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('şrkt_name', models.CharField(max_length=50)),
                ('şrkt_tel', models.CharField(max_length=50)),
                ('şrkt_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('tc_kimlik_no', models.CharField(max_length=11)),
                ('telefon', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('cihaz', models.CharField(max_length=50)),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('arıza', models.CharField(max_length=50)),
                ('açıklama', models.CharField(max_length=50)),
                ('geliş_tarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('son_degisiklik_tarihi', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
