# Generated by Django 3.2.20 on 2023-09-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ayarlar',
            old_name='username',
            new_name='usernameqv',
        ),
    ]
